apiVersion: v1
kind: Service
metadata:
  name: clickhouse-mcp-server
  namespace: default
spec:
  selector:
    app: clickhouse-mcp-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    # nodePort: 30080
  type: ClusterIP
#  type: NodePort
